### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by maijams** [henriimmonen/shortestroute#1]
Projekti näyttää olevan jo melko hyvässä vaiheessa. Koodia on pääosin jaoteltu hyvin luokkiin ja metodeihin ja kirjoitusasu on selkeää. Refaktoroitavaa varmasti löytyy vielä, kuten viikkoraportissakin todettiin niin ehkä eniten varmaan JPS-algoritmin kohdalla, erityisesti viimeinen metodi tarkista_pakotetut_naapurit(). Tuo kuitenkin ihan oletettavaa vielä tässä vaiheessa kurssia. :) Kysymyksiä herätti käyttöliittymä, onko tarkoitus että käyttäjä voi jossain vaiheessa myös valita alku- ja loppupisteet kartalta? Tämä voisi olla hyvä lisäominaisuus ja mahdollisesti helpottaisi myös suorituskyvyn testausta, jos vaan jää aikaa toteutukselle. Kokeilin testikartan lisäksi projektin mukana tullutta "sydney"-karttaa ja sen kohdalla luettavuus hieman kärsi tekstikäyttöliittymässä. Olisiko mahdollista siirtää molempien algoritmien tulokset tulostuksessa viimeiseksi niin nuo tulosteet löytäisi helpommin ja vertailu olisi helpompaa? Nyt joutui ison kartan takia skrollaamaan reilusti ylös ennenkuin tuloksia löytyi. Muilta osin näytti ihan hyvältä ja algoritmit toimivilta :)  (Projekti kloonattu 3.12 klo 22.30)

**Comment by henriimmonen** [comment]
Kiitos hyvistä kommenteista!
