### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by hartonenolli** [henriimmonen/shortestroute#2]
# Huomioita tällä hetkellä projektista

Pohja ladattu **09.12.2022 klo 23:20**

# Dokumentaatiosta

Määrittelydokumentti on erinomainen. Oli kivasti kerrottu miksi olit valinnut JPS algoritmin.

Hyvä idea on myös hakea kartat linkkaamaltasi sivulta.

**Valitettavasti en saanut käynnistettyä ohjelmaa käyttöohjeiden mukaan**
- Ohjeissa neuvotaan kopioimaan repositorio ja menemään virtuaaliympäristöön
- Sitten poetryn asennus
- Ohjelman kerrotaan käynnistyvän virtuaaliympäristössä komennolla: *poetry src/index.py*
  - Tästä syntyy virheilmoitus: The command "poetry src/index.py" does not exist.
- Sain kuitenkin ohjelman käynnistyttyä komennolla: *python3 src/index.py*

# Ohjelmasta terminaalilla

Ohjelma on selvän näköinen. Kuljettujen pisteiden tulostus *-merkin lisäksi helpottaa reitin seurantaa.

Ohjelmassa näyttää olevan joku *bugi*. JPS algoritmi hakee reitin, joka hyppää yhden rivin yli. Lähtöpisteestä (0,0) mennään suoraan (2,2), eli 1-rivi hypätään suoraan yli.

# Testit ja pylint

Pylint on erinomainen ja testit hyvällä mallilla. JPS on toki vaikea testata automaattisin testein, mutta senkin kattavuus on ihan hyväksyttävä.

# Koodista

Koodin kommentointi on kattavaa koko ohjelman. Hyviä ja selviä kommentteja. Ainoastaan *index.py* tiedostoon olisin toivonut vähän kattavamman kommentin, jos se on mahdollista.

Huomasin, että luokkanimissä olet käyttänyt ()-merkkejä nimen perässä. Tämä on toki ihan ok, mutta luokat toimii ilmankin niitä. Jos tämä on tyylillinen päätös, niin tämä huomio kannattaa ohittaa.

JPS- algoritmi käyttää erinomaisesti apufunktiot tiedostoa. Olet tällä tavoin saanut tiedoston monimutkaisuutta vähennettyä.

# Summa summarum

Hyvältä vaikuttaa ohjelma. Koodisi noudattaa hyvän ohjelmoinni perjaitteita.

Käyttöohje kannattaa korjata ja JPS oli se yksi bugi.

Kokonaiskuva oli kuitenkin miellyttävää tutustua ohjelmaasi.

Jatka samaan malliin!

-Olli

**Comment by henriimmonen** [comment]
Kiitoksia hyvistä kommenteista! 

Kommentoitu bugi liittyi luultavasti terminaaliin tulostettuun JPS-algoritmin reittiin joka oli lähinnä debuggausta varten (nyt poistettu). Reitti näytti pelkät hyppypisteet, joten tämän vuoksi kaikkia rivejä ei tulostettu tähän listaan.
